https://www.perplexity.ai/search/b99dd1ac-2d40-4f7d-ba29-2972671abf18

In [11]:
import numpy as np

np.random.seed(5678)
scores = np.random.randint(50, 101, size=(50, 5))
scores

array([[ 73,  68,  63,  86,  64],
       [ 81,  69,  64,  78,  80],
       [ 65,  55,  68,  56,  50],
       [ 55,  69,  76,  65,  59],
       [ 69,  69,  75,  74,  53],
       [ 75,  67,  92,  99,  71],
       [ 54,  50,  84,  68,  62],
       [ 63,  91,  52,  71,  78],
       [ 68,  98,  70,  71,  96],
       [ 82,  65,  82,  85,  63],
       [ 98,  64, 100,  88,  61],
       [ 58,  86,  84,  76,  70],
       [ 69,  89,  94,  73,  67],
       [ 91,  62,  83,  73,  76],
       [ 79,  52,  87, 100,  65],
       [ 96,  72,  88,  63,  65],
       [ 65,  87,  69,  73,  74],
       [ 63,  80,  84,  58,  88],
       [ 51,  55,  88,  71,  97],
       [ 97,  82,  90,  84,  59],
       [ 52,  52,  71,  79,  82],
       [ 81,  65,  68,  81,  87],
       [ 93,  63,  68,  96,  87],
       [ 57,  58,  50,  83,  99],
       [ 55,  90,  67,  86,  69],
       [ 73,  90,  54,  73,  60],
       [ 79,  59,  63,  93,  51],
       [ 92,  91,  67,  79,  92],
       [ 60,  82,  96,  96,  62],
       [ 80,  63,  74,  96,  51],
       [ 51,  92,  72,  86,  52],
       [ 71,  95,  88,  54,  94],
       [ 71,  70,  57,  62,  94],
       [ 80,  87,  57,  64,  85],
       [ 63,  92,  68,  86,  92],
       [ 82,  70,  92,  97,  79],
       [ 85,  81,  69,  55,  88],
       [ 96,  52,  67,  79,  86],
       [ 54,  62,  56,  94,  53],
       [ 95,  71,  81,  81,  92],
       [ 80,  75,  80,  57,  72],
       [ 75,  96,  82,  83,  72],
       [ 99,  91,  98, 100,  90],
       [ 82,  99,  61,  91,  58],
       [100,  55,  98,  63,  62],
       [ 52,  85,  57,  62,  81],
       [ 92,  60,  52,  55,  99],
       [ 58,  90,  55,  98,  71],
       [ 84,  63,  90,  68,  92],
       [ 89,  65,  65,  50,  80]])

In [21]:
import pandas as pd

df = pd.DataFrame(scores,columns=["國文", "英文", "數學", "生物", "物理"],index=[f"學生{x}" for x in range(1,51)])
type(df)

pandas.core.frame.DataFrame

In [17]:
[x**2 for x in range(10) if x < 4]

[0, 1, 4, 9]

In [28]:
df.columns.name = "科目"
df.index.name = "姓名"
df

科目     國文  英文   數學   生物  物理
姓名
學生1    73  68   63   86  64
學生2    81  69   64   78  80
學生3    65  55   68   56  50
學生4    55  69   76   65  59
學生5    69  69   75   74  53
學生6    75  67   92   99  71
學生7    54  50   84   68  62
學生8    63  91   52   71  78
學生9    68  98   70   71  96
學生10   82  65   82   85  63
學生11   98  64  100   88  61
學生12   58  86   84   76  70
學生13   69  89   94   73  67
學生14   91  62   83   73  76
學生15   79  52   87  100  65
學生16   96  72   88   63  65
學生17   65  87   69   73  74
學生18   63  80   84   58  88
學生19   51  55   88   71  97
學生20   97  82   90   84  59
學生21   52  52   71   79  82
學生22   81  65   68   81  87
學生23   93  63   68   96  87
學生24   57  58   50   83  99
學生25   55  90   67   86  69
學生26   73  90   54   73  60
學生27   79  59   63   93  51
學生28   92  91   67   79  92
學生29   60  82   96   96  62
學生30   80  63   74   96  51
學生31   51  92   72   86  52
學生32   71  95   88   54  94
學生33   71  70   57   62  94
學生34   80  87   57   64  85
學生35   63  92   68   86  92
學生36   82  70   92   97  79
學生37   85  81   69   55  88
學生38   96  52   67   79  86
學生39   54  62   56   94  53
學生40   95  71   81   81  92
學生41   80  75   80   57  72
學生42   75  96   82   83  72
學生43   99  91   98  100  90
學生44   82  99   61   91  58
學生45  100  55   98   63  62
學生46   52  85   57   62  81
學生47   92  60   52   55  99
學生48   58  90   55   98  71
學生49   84  63   90   68  92
學生50   89  65   65   50  80